//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StringingApplication.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Request
    {
        public int RequestId { get; set; }
        public Nullable<int> ClubId { get; set; }
        public Nullable<int> MemberId { get; set; }
        public Nullable<int> MainStringsId { get; set; }
        public Nullable<int> CrossStringsId { get; set; }
        public Nullable<int> MainTension { get; set; }
        public Nullable<int> CrossTension { get; set; }
        public Nullable<System.DateTime> DateReceived { get; set; }
        public Nullable<System.DateTime> DateCompleted { get; set; }
        public Nullable<bool> IsDone { get; set; }
    
        public virtual Club Club { get; set; }
        public virtual Member Member { get; set; }
        public virtual String String { get; set; }
        public virtual String String1 { get; set; }
    }
}
